# Test notebook


In [1]:
%load_ext autoreload
%autoreload 1

In [2]:
from vision_models.utils import VisionUtils

vutil = VisionUtils()    
vutil.set_seed()
vutil.print_python_version()
vutil.print_tf_version()
vutil.print_tf_gpu_support()





2024-07-21 23:25:29.722580: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-21 23:25:29.722632: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-21 23:25:29.724595: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-21 23:25:29.731935: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
Tensorflow version: 2.16.2
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


2024-07-21 23:25:31.854741: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-21 23:25:31.903395: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-21 23:25:31.907247: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [4]:
import sys
print(sys.executable)
import tensorflow as tf

from vision_models.dataset import VisionDataset

vision_ds = VisionDataset()
train_dataset, val_dataset, encoders = vision_ds.create_dataset(batch_size=1)

/opt/conda/envs/vision/bin/python
Reading CSV file /opt/dataset/train.csv
Reading CSV file /opt/dataset/train_series_descriptions.csv
Reading CSV file /opt/dataset/train_label_coordinates.csv
Maximum number of subdirectories across all studies: 6
Shape of the DataFrame: (1975, 26)
Columns of the DataFrame: Index(['study_id', 'spinal_canal_stenosis_l1_l2',
       'spinal_canal_stenosis_l2_l3', 'spinal_canal_stenosis_l3_l4',
       'spinal_canal_stenosis_l4_l5', 'spinal_canal_stenosis_l5_s1',
       'left_neural_foraminal_narrowing_l1_l2',
       'left_neural_foraminal_narrowing_l2_l3',
       'left_neural_foraminal_narrowing_l3_l4',
       'left_neural_foraminal_narrowing_l4_l5',
       'left_neural_foraminal_narrowing_l5_s1',
       'right_neural_foraminal_narrowing_l1_l2',
       'right_neural_foraminal_narrowing_l2_l3',
       'right_neural_foraminal_narrowing_l3_l4',
       'right_neural_foraminal_narrowing_l4_l5',
       'right_neural_foraminal_narrowing_l5_s1',
       'left_subart

2024-07-21 23:25:45.648522: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-21 23:25:45.653576: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-21 23:25:45.656911: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

Splitting dataset
Dataset created


In [7]:
# if train_dataset is not None:
#     for data, labels in train_dataset.take(5):  # Look at 5 samples
#             print("Sample labels:", labels.numpy())
#             print()

Sample labels: [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

Sample labels: [[1 1 1 1 1 1 1 1 0 2 1 1 0 0 1 1 1 1 1 1 1 1 0 0 0]]

Sample labels: [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

Sample labels: [[1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 2 2 0 2]]

Sample labels: [[1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1]]



2024-07-21 23:23:01.366849: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [5]:
vutil.print_dataset_info(train_dataset, print_labels=True)

Images shape: tf.Tensor([  1   6  58 224 224   1], shape=(6,), dtype=int32)
Series descriptions shape: tf.Tensor([1 6], shape=(2,), dtype=int32)
Label coordinates shape: tf.Tensor([1 6], shape=(2,), dtype=int32)
Labels shape: tf.Tensor([ 1 25], shape=(2,), dtype=int32)
Subdir 0 image tensor shape: tf.Tensor([  6  58 224 224   1], shape=(5,), dtype=int32)


2024-07-21 23:26:10.511467: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
